### ISSUE TITLE
Scale out?

### ISSUE THREAD

**Issue by haizaar** [KSDaemon/wiola#12]
Good day, 

Apologies for asking a feature question, but I didn't find any discussion group for this project.

Since Wiola uses Redis as a backing store, is it correct to assume that I can run multiple Wiola instances (i.e. nginx instances) against a single Redis (cluster) to achieve scale-out capabilities?

I'm mainly looking for a scale-out alternative to a crossbar.io where my whole infrastructure would not depend on a single container running crossbar.

**Comment by KSDaemon** [comment]
Hi, @haizaar! Great that you are using Wiola!
And YES! You're absolutely right! You can scale Wiola by adding more nginx instances and using Redis cluster under the hood.
You can ask anything related Wiola here. 
Btw, i also have a plans to add postgresql storage provider. That will be good option in case you already have a postgresql in your environment (less infrastructure to maintain)

**Comment by KSDaemon** [comment]
That was easy one :)
