### ISSUE TITLE
Properly handle incorrect realm

### ISSUE THREAD

**Issue by haizaar** [KSDaemon/wiola#16]
Today if a client tries to connect to a realm that is not defined on wiola router, the following cryptic error is thrown (in Python):

```
2018-09-21T18:50:29 Traceback (most recent call last):
  File "/home/python3.7/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage
    for msg in self._serializer.unserialize(payload, isBinary):
  File "/home/python3.7/site-packages/autobahn/wamp/serializer.py", line 131, in unserialize
    msg = Klass.parse(raw_msg)
  File "/home/python3.7/site-packages/autobahn/wamp/message.py", line 977, in parse
    details = check_or_raise_extra(wmsg[1], u"'details' in ABORT")
  File "/home/python3.7/site-packages/autobahn/wamp/message.py", line 274, in check_or_raise_extra
    raise ProtocolError(u"{0}: invalid type {1} for WAMP extra".format(message, type(value)))
autobahn.wamp.exception.ProtocolError: 'details' in ABORT: invalid type <class 'list'> for WAMP extra
```

**Comment by KSDaemon** [comment]
Hm.... Interesting... 
Wiola replies with correct answer `[3,{},"wamp.error.no_such_realm"]`
Second parameter is just empty dictionary as defined in WAMP spec.

**Comment by haizaar** [comment]
Well, Python says it gets the list :)
May be the issue is that the dict is serialized as list? May be due to Lua not having distinct types for those?

**Comment by KSDaemon** [comment]
No-no-no) 
Answer i've shown — is right before sending via net, so no further modification/serialization is done with that. 
And yes, you're right: lua just has tables :) BUT That is one of the first issues i've got and i've tried different serializators libs and taken one, that can handle that properly. In that case i've mannualy set that empty lua table should be serialized as dictionary.
```lua
setmetatable({}, { __jsontype = 'object' }),
```

**Comment by KSDaemon** [comment]
btw, what serializer is used? JSON or MSGPACK?

**Comment by KSDaemon** [comment]
@haizaar are there any news from python side? Did you have time to investigate?

**Comment by KSDaemon** [comment]
As there are no more info, and it seems to work in our test environments, i'm closing for now...
Feel free to reopen.
