### ISSUE TITLE
ws-handler.lua:128: Failed to read redis reply: timeout

### ISSUE THREAD

**Issue by raimisiber** [KSDaemon/wiola#17]
error.log

2019/03/13 11:05:38 [error] 9628#0: *57 [lua] ws-handler.lua:128: Failed to read redis reply: timeout, client: 192.168.88.66, server: , request: "GET /ws HTTP/1.1", host: "192.168.88.210:7000"

redis

redis redis-server.sock> MONITOR
OK
1552446277.911764 [0 127.0.0.1:51624] "select" "5"
1552446277.911902 [5 127.0.0.1:51624] "hgetall" "wiSes1610537756091313"
1552446277.912125 [5 127.0.0.1:51624] "hgetall" "wiRealmrealm1Subs"
1552446277.912277 [5 127.0.0.1:51624] "hgetall" "wiSes1610537756091313RPCs"
1552446277.912444 [5 127.0.0.1:51624] "del" "wiSes1610537756091313RPCs"
1552446277.912592 [5 127.0.0.1:51624] "del" "wiSes1610537756091313RevRPCs"
1552446277.912737 [5 127.0.0.1:51624] "del" "wiSes1610537756091313Challenge"
1552446277.912885 [5 127.0.0.1:51624] "srem" "wiRealmrealm1Sessions" "1610537756091313"
1552446277.913054 [5 127.0.0.1:51624] "scard" "wiRealmrealm1Sessions"
1552446277.913200 [5 127.0.0.1:51624] "srem" "wiolaRealms" "realm1"
1552446277.913346 [5 127.0.0.1:51624] "del" "wiSes1610537756091313Data"
1552446277.913491 [5 127.0.0.1:51624] "del" "wiSes1610537756091313"
1552446277.913658 [5 127.0.0.1:51624] "srem" "wiolaSessionsIds" "1610537756091313"
1552446278.417726 [0 127.0.0.1:51626] "select" "5"
1552446278.417925 [5 127.0.0.1:51626] "sismember" "wiolaSessionsIds" "1023787888808267"
1552446278.418083 [5 127.0.0.1:51626] "sadd" "wiolaSessionsIds" "1023787888808267"
1552446278.418392 [5 127.0.0.1:51626] "hmset" "wiSes1023787888808267" "connId" "57" "encoding" "json" "sessId" "1023787888808267" "dataType" "text" "isWampEstablished" "0" "wamp_protocol" "wamp.2.json"
1552446278.418771 [0 127.0.0.1:51628] "select" "5"
1552446278.418963 [5 127.0.0.1:51628] "subscribe" "__keyspace@5__:wiSes1023787888808267Data"
1552446278.482983 [5 127.0.0.1:51626] "hgetall" "wiSes1023787888808267"
1552446278.483338 [5 127.0.0.1:51626] "hmset" "wiSes1023787888808267" "wampFeatures" "{\"roles\":{\"callee\":{\"features\":{\"pattern_based_registration\":true,\"shared_registration\":true,\"call_trustlevels\":true,\"caller_identification\":true}},\"subscriber\":{\"features\":{\"publication_trustlevels\":true,\"pattern_based_subscription\":true}},\"caller\":{\"features\":{\"progressive_call_results\":true,\"call_canceling\":true,\"call_timeout\":true,\"caller_identification\":true}},\"publisher\":{\"features\":{\"publisher_exclusion\":true,\"publisher_identification\":true,\"subscriber_blackwhite_listing\":true}}},\"agent\":\"Wampy.js v6.2.1\"}" "connId" "57" "encoding" "json" "realm" "realm1" "sessId" "1023787888808267" "dataType" "text" "isWampEstablished" "1" "wamp_protocol" "wamp.2.json"
1552446278.483689 [5 127.0.0.1:51626] "sismember" "wiolaRealms" "realm1"
1552446278.483991 [5 127.0.0.1:51626] "sadd" "wiolaRealms" "realm1"
1552446278.484197 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.session.count"
1552446278.484355 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.session.list"
1552446278.484524 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.session.get"
1552446278.484675 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.subscription.list"
1552446278.484826 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.subscription.lookup"
1552446278.484975 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.subscription.match"
1552446278.485124 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.subscription.get"
1552446278.485272 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.subscription.list_subscribers"
1552446278.485439 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.subscription.count_subscribers"
1552446278.485593 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.registration.list"
1552446278.485761 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.registration.lookup"
1552446278.485911 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.registration.match"
1552446278.486059 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.registration.get"
1552446278.486208 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.registration.list_callees"
1552446278.486357 [5 127.0.0.1:51626] "sismember" "wiRealmrealm1RPCs" "wamp.registration.count_callees"
1552446278.486507 [5 127.0.0.1:51626] "sadd" "wiRealmrealm1Sessions" "1023787888808267"
1552446278.486658 [5 127.0.0.1:51626] "rpush" "wiSes1023787888808267Data" "[2,1023787888808267,{\"roles\":{\"dealer\":{\"features\":{\"call_canceling\":true,\"registration_meta_api\":true,\"caller_identification\":true,\"pattern_based_registration\":true,\"progressive_call_results\":true,\"call_timeout\":true,\"session_meta_api\":true}},\"broker\":{\"features\":{\"publisher_exclusion\":true,\"pattern_based_subscription\":true,\"publisher_identification\":true,\"subscriber_blackwhite_listing\":true,\"subscription_meta_api\":true,\"session_meta_api\":true}}},\"agent\":\"wiola/Lua v0.12.0\"}]"
1552446278.486919 [5 127.0.0.1:51626] "hget" "wiRealmrealm1Subs" "wamp.session.on_join"
1552446338.420635 [0 127.0.0.1:51630] "select" "5"
1552446338.420829 [5 127.0.0.1:51630] "hgetall" "wiSes1023787888808267"
1552446338.421043 [5 127.0.0.1:51630] "hgetall" "wiRealmrealm1Subs"
1552446338.421197 [5 127.0.0.1:51630] "hgetall" "wiSes1023787888808267RPCs"
1552446338.421361 [5 127.0.0.1:51630] "del" "wiSes1023787888808267RPCs"
1552446338.421507 [5 127.0.0.1:51630] "del" "wiSes1023787888808267RevRPCs"
1552446338.421666 [5 127.0.0.1:51630] "del" "wiSes1023787888808267Challenge"
1552446338.421828 [5 127.0.0.1:51630] "srem" "wiRealmrealm1Sessions" "1023787888808267"
1552446338.421984 [5 127.0.0.1:51630] "scard" "wiRealmrealm1Sessions"
1552446338.422131 [5 127.0.0.1:51630] "srem" "wiolaRealms" "realm1"
1552446338.422279 [5 127.0.0.1:51630] "del" "wiSes1023787888808267Data"
1552446338.422426 [5 127.0.0.1:51630] "del" "wiSes1023787888808267"
1552446338.422588 [5 127.0.0.1:51630] "srem" "wiolaSessionsIds" "1023787888808267"

**Comment by KSDaemon** [comment]
Hi @raimisiber Can you provide more information about issue? When/how does this happens? How can it be reproduced?

**Comment by raimisiber** [comment]
i want connect wampy to wiola, then i get error at error log..did i do something wrong?

index.html


<script src="browser/wampy-all.min.js"></script>
	<script type="text/javascript">
		ws = new Wampy('ws://192.168.88.210:7000/ws', {
		    realm: 'realm1',
		    onConnect: () => {
		        console.log('Connected to Router!');
		    }
		});
	</script>
</head>

nginx.conf

worker_processes	3;
error_log		logs/error.log;

events {
	worker_connections	4096;
}

http {

    # set search paths for pure Lua external libraries (';;' is the default path):
    # add paths for wiola and msgpack libs
    lua_package_path '/opt/openresty/lualib/wiola/?.lua;/opt/openresty/lualib/lua-MessagePack/?.lua;;';

    init_worker_by_lua_block {
        -- Initializing math.randomseed for every worker/luaVM
        local f = io.open('/dev/random', 'rb')
        local seed
        if f then
            local b1, b2, b3, b4 = string.byte(f:read(4), 1, 4)
            seed = b1 * 0x1000000 + b2 * 0x10000 + b3 * 0x100 + b4
            f:close()
        else
            seed = ngx.time() + ngx.worker.pid()
        end
        math.randomseed(seed)
        math.randomseed = function()end
    }


    init_by_lua_block {
        -- Wiola configuration. You can read more in description of .configure() method below.
        local cfg = require "wiola.config"
        cfg.config({
            socketTimeout = 1000,           -- one second
            maxPayloadLen = 65536,
            realms = { "realm1" },
            store = "redis",
            storeConfig = {
                host = "unix:///var/run/redis/redis-server.sock",  -- Optional parameter. Can be hostname/ip or socket path  
                --port = 6379                     -- Optional parameter. Should be set when using hostname/ip
                                                  -- Omit for socket connection
                --db = 5                          -- Optional parameter. Redis db to use
            },
            callerIdentification = "auto",        -- Optional parameter. auto | never | always
            cookieAuth = {                        -- Optional parameter. 
                authType = "none",                -- none | static | dynamic
                cookieName = "wampauth",
                staticCredentials = nil, --{
                    -- "user1", "user2:password2", "secretkey3"
                --},
                authCallback = nil
            },
            wampCRA = {                           -- Optional parameter.
                authType = "none",                -- none | static | dynamic
                staticCredentials = nil, --{
                    -- user1 = { authrole = "userRole1", secret="secret1" },
                    -- user2 = { authrole = "userRole2", secret="secret2" }
                --},
                challengeCallback = nil,
                authCallback = nil
            },
            trustLevels = {                       -- Optional parameter.
                authType = "none",                -- none | static | dynamic
                defaultTrustLevel = nil,
                staticCredentials = {
                    byAuthid = {
                        --{ authid = "user1", trustlevel = 1 },
                        --{ authid = "admin1", trustlevel = 5 }
                    },
                    byAuthRole = {
                        --{ authrole = "user-role", trustlevel = 2 },
                        --{ authrole = "admin-role", trustlevel = 4 }
                    },
                    byClientIp = {
                        --{ clientip = "127.0.0.1", trustlevel = 10 }
                    }
                },
                authCallback = nil -- function that accepts (client ip address, realm,
                                   -- authid, authrole) and returns trust level
            },
            metaAPI = {                           -- Expose META API ? Optional parameter.
                session = true,
                subscription = true,
                registration = true
            }
        })

        -- If you want automatically clean up redis db during nginx restart uncomment next two lines
        -- for this to work, you need redis-lua library
        -- Use it only with lua_code_cache on; !!!
        --local wflush = require "wiola.flushdb"
        --wflush.flushAll()
    }

    # Configure a vhost
    server {
       listen	chat.projeksiber.com:7000;
       # example location for websocket WAMP connection
       location /ws {
          set $wiola_max_payload_len 65535; # Optional parameter. Set the value to suit your needs
          
          lua_socket_log_errors off;
          lua_check_client_abort on;
    
          # This is needed to set additional websocket protocol headers
          header_filter_by_lua_file $document_root/lua/wiola/headers.lua;
          # Set a handler for connection
          content_by_lua_file $document_root/lua/wiola/ws-handler.lua;
       }
    
       # example location for a lightweight POST event publishing
       location /wslight {
          lua_socket_log_errors off;
          lua_check_client_abort on;
    
          content_by_lua_file $document_root/lua/wiola/post-handler.lua;
       }
    
    }
}

**Comment by KSDaemon** [comment]
did you connected to router and then after some time received this error?

**Comment by raimisiber** [comment]
yes, that right, after some time i'm received this error

 [error] 19502#19502: *40 [lua] ws-handler.lua:128: Failed to read redis reply: timeout, client: 192.168.88.55, server: , request: "GET /ws HTTP/1.1", host: "192.168.88.210:7000"
