### ISSUE TITLE
Please make Wiola available on Luarocks

### ISSUE THREAD

**Issue by mingfang** [KSDaemon/wiola#3]
It would be great if I can easily install Wiola using Luarocks.

**Comment by KSDaemon** [comment]
Hi @mingfang ! Great idea! Right now, i don't know how it's easy or not, because Wiola heavily relies on openresty. But i'll check such possibility. thanks!

**Comment by KSDaemon** [comment]
Hi, @mingfang! I've just got a little time to spend on this issue. At first glance, not all dependencies are available through luarocks. I've found luarestyredis, lua-resty-libcjson and lua-messagepack. There is no lua-resty-websocket. 
How do you think, how should we specify rockspec file? Without this dep? I don't want to include that in wiola package. Or it's ok to leave this and just mention this in documentation?

**Comment by mingfang** [comment]
@KSDaemon Thanks for working on this.

lua-resty-websocket is already bundled in openresty so I think it will be ok to just mention this in documentation.

**Comment by KSDaemon** [comment]
Hi, @mingfang sorry for so delayed answer, overworked %) But published! :)
