### ISSUE TITLE
Installation and Usage

### ISSUE THREAD

**Issue by abdulrahmanmadeni** [KSDaemon/wiola#4]
Hi

Guide me how to do the installation of wiola after I installed openresty in my ubuntu server?

**Comment by KSDaemon** [comment]
Hi @abdulrahmanmadeni ! Have you read and done all the things, written in docs?
All you need is edit nginx.conf:
* Add path for wiola lib, like: `lua_package_path '/usr/local/lualib/wiola/?.lua;`
* Add wiola header handler for websocket location, like: `header_filter_by_lua_file $document_root/lua/wiola/headers.lua;`
* Add wiola request handler for the same websocket location, like: `content_by_lua_file $document_root/lua/wiola/handler.lua;`

**Comment by abdulrahmanmadeni** [comment]
ok... it was done... but could not find libcjson.so ... i tried follow the
instruction given... but still cannot run. Please adevice

**Comment by abdulrahmanmadeni** [comment]
it works now for libcjson.so .... but another problem come...
"attemp to index local 'data' (a nil value)"
at wiola.lua file line 278....

please advice me on this...

**Comment by KSDaemon** [comment]
@abdulrahmanmadeni Can you create a gist with nginx.conf data?
Also, do you use src or build (min) version?

**Comment by abdulrahmanmadeni** [comment]
this is my nginx.conf

daemon off;
master_process off;
error_log stderr info;
events { worker_connections 256; }
http {
    types {
        text/html html;
        text/css css;
        application/javascript js;
    }
    client_body_temp_path logs;
    fastcgi_temp_path logs;
    proxy_temp_path logs;
    scgi_temp_path logs;
    uwsgi_temp_path logs;
    access_log off;
    gzip on;
    gzip_types text/css application/javascript;

	lua_package_path "$prefix/api/?.lua;$prefix/lib/?.lua;/usr/local/openresty/lua-MessagePack/?.lua;;";
    lua_shared_dict db 1M;
    init_by_lua "app = require 'api.app'";
    server {
        listen 8080;
        #lua_code_cache off;
        location /api {
            content_by_lua "app:run()";
        }
		
		location /ws {
			lua_socket_log_errors off;
			lua_check_client_abort on;

			# This is needed to set additional websocket protocol headers
			header_filter_by_lua_file /home/project/wiola/build/headers.lua;
			# Set a handler for connection
			content_by_lua_file /home/project/wiola/build/handler.lua;
		}

		# example location for a lightweight POST event publishing
		location /wslight/ {
			lua_socket_log_errors off;
			lua_check_client_abort on;
			content_by_lua_file /home/project/wiola/build/post-handler.lua;
		}
    } 
}

which one is src? and which one is build version?

**Comment by abdulrahmanmadeni** [comment]
Hi

It was fixed by replacing "resty.libcjson" in wiola and replace it with
cjson library

**Comment by KSDaemon** [comment]
ough... @abdulrahmanmadeni sorry, i've just forgotten that i switched from cjson library to resty.libcjson, and did not update the docs! 
Btw, i switched to resty.libcjson because in cjson you can not specify how to serialize empty object attributes. All you have is to choose between: all empty objects will be serialized as empty arrays ([]) or empty objects ({}), and you can not instruct cjson to use any variant on specific attribute.

**Comment by abdulrahmanmadeni** [comment]
em.... what I should I do now? where can I get library "resty.libcjson"?

**Comment by KSDaemon** [comment]
That's easy. You can use luarocks, if you are familiar with that.
``` luarocks install lua-resty-libcjson ```
Or just place libcjson.lua somewhere in your package.path, preferably under resty directory. If you are using OpenResty, the default location would be something like /usr/local/openresty/lualib/resty.
For more info on module, check: https://github.com/bungle/lua-resty-libcjson

**Comment by abdulrahmanmadeni** [comment]
hope u don't close yet.... i still have problem with this

**Comment by KSDaemon** [comment]
I'm here :) What's up?

**Comment by abdulrahmanmadeni** [comment]
I am almost to finish it.... lets me do the testing first

**Comment by KSDaemon** [comment]
Well, i assume, everything is ok. So closing.

**Comment by abdulrahmanmadeni** [comment]
Lets it closed....first... if any bugs find later will contact u again
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
