### ISSUE TITLE
Example code always results in error 500 for me

### ISSUE THREAD

**Issue by tpimh** [KSDaemon/wiola#5]
I have installed wiola using luarocks to openresty location, I have included example config to my `nginx.conf` for lapis.
Here is my full `nginx.conf`:

    worker_processes ${{NUM_WORKERS}};
    error_log stderr notice;
    daemon off;
    pid logs/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      include mime.types;
      
      lua_package_path '/opt/openresty/luajit/share/lua/5.1/?.lua;;';

      server {
        listen ${{PORT}};
        lua_code_cache ${{CODE_CACHE}};

        location / {
          default_type text/html;
          content_by_lua '
            require("lapis").serve("app")
          ';
        }

        location /static/ {
          alias static/;
        }

        location /favicon.ico {
          alias static/favicon.ico;
        }

        location /ws/ {
          lua_socket_log_errors off;
          lua_check_client_abort on;

          header_filter_by_lua_file /opt/openresty/luajit/share/lua/5.1/wiola/headers.lua;
          content_by_lua_file /opt/openresty/luajit/share/lua/5.1/wiola/handler.lua;
        }

        location /wslight/ {
          lua_socket_log_errors off;
          lua_check_client_abort on;

          content_by_lua_file /opt/openresty/luajit/share/lua/5.1/wiola/post-handler.lua;
        }
      }
    }

On `/ws/` I get this syntax error:

    2016/09/30 16:40:22 [error] 18632#0: *1 failed to load external Lua file "/opt/openresty/luajit/share/lua/5.1/wiola/handler.lua": /opt/openresty/luajit/share/lua/5.1/wiola/handler.lua:25: unexpected symbol near ')', client: 192.168.122.1, server: , request: "GET /ws/ HTTP/1.1", host: "192.168.122.170:8080"

On `/wslight/` I get this runtime error:

    2016/09/30 16:42:35 [error] 18632#0: *2 lua entry thread aborted: runtime error: /opt/openresty/luajit/share/lua/5.1/wiola.lua:605: bad argument #1 to 'decode' (string expected, got nil)
    stack traceback:
    coroutine 0:
    	[C]: in function 'decode'
    	/opt/openresty/luajit/share/lua/5.1/wiola.lua:605: in function 'processPostData'
    	/opt/openresty/luajit/share/lua/5.1/wiola/post-handler.lua:19: in function </opt/openresty/luajit/share/lua/5.1/wiola/post-handler.lua:1>, client: 192.168.122.1, server: , request: "GET /wslight/ HTTP/1.1", host: "192.168.122.170:8080"

Maybe my configuration is wrong? Have you tried setting up Wiola with Lapis?

**Comment by KSDaemon** [comment]
Hi, @tpimh! Well, i'll try to look whats wrong ASAP.

**Comment by KSDaemon** [comment]
Arggghhhh! Sorry, my mistake. There was a 2 lines debug message, that was not fully deleted during build process. For a quick fix, you can just delete 25th line in handler.lua. 
I'll fix it on next week.

**Comment by KSDaemon** [comment]
Thanks for pointing out!

**Comment by KSDaemon** [comment]
To /wslight/ URI you should “POST” wamp message (in body), but not “GET”.

**Comment by tpimh** [comment]
Thank you for rapid response. It seems to work now.
I will try to study it more on the weekend.
